baseURL: https://mpdesouza.com
theme: anatole
title: Marcos' Blog
languageCode: en

summarylength: 10
enableEmoji: true

googleAnalytics: UA-114151448-3

params:
  permalinks:
    blog: /:slug/

  gravatar: marcos.souza.org@gmail.com
  profilePicture: images/pp.jpg

  author: Marcos Paulo de Souza
  license: CC BY-SA 4.0
  licenseURL: https://creativecommons.org/licenses/by-sa/4.0
  title: Hi I'm Marcos
  description: Welcome to my personal homepage
  copyright: 2020-{{ YEAR }}

  socialIcons:
    - icon: fab fa-linkedin
      title: Linkedin
      url: https://www.linkedin.com/in/marcospsouza/
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/marcosps
    - icon: fab fa-twitter
      title: Twitter
      url: https://twitter.com/omarcossouza

menu:
  main:
  - name: Home
    identifier: home
    weight: 10
    url: /
  - name: About Me
    identifier: about
    weight: 20
    url: /about-me/

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: dracula
    ntabWidth: 4
